DROP TABLE cellwall.from_mysql_dblink
DROP TABLE cellwall.from_mysql_db     
DROP TABLE cellwall.from_mysql_family 
DROP TABLE cellwall.from_mysql_genome 
DROP TABLE cellwall.from_mysql_groups 
DROP TABLE cellwall.from_mysql_idxref 
DROP TABLE cellwall.from_mysql_parameters
DROP TABLE cellwall.from_mysql_search    
DROP TABLE cellwall.from_mysql_species   
DROP TABLE cellwall.from_mysql_subfamily 
DROP TABLE cellwall.from_mysql_users     
DROP TABLE cellwall.from_mysql_sequence  
DROP TABLE cellwall.from_mysql_seqtags   
DROP TABLE cellwall.from_mysql_seqfeature
DROP TABLE cellwall.from_mysql_seqlocation
