#!/bin/bash

set -e

stat code > /dev/null || stat data > /dev/null || \
        (echo "ERROR: You must run this script from the root of the project dir"; exit 1)

~/src/guidance.v1.41/www/Guidance/guidance.pl \
  --msaProgram MAFFT \
  --seqType aa  \
  --mafft  ~/src/mafft-7.130-with-extensions/scripts/mafft \
  \
  --seqFile data/250-add-to-family/201402182BNZGRYYXK.fasta \
  --outDir data/260-re-align-msa/gh43
