#!/usr/bin/ruby

SNAME = File.basename(__FILE__)
SDIR  = File.dirname(File.expand_path(__FILE__))

DROPOUTS = [/^([^|]*)\|([^|]*)\|([^|]*)_ARATH/,
            /^([^|]*)\|([^|]*)\|([^|]*)_ORYSA/,

            # Rice Variants (http://www.uniprot.org/taxonomy/4530)
            /^([^|]*)\|([^|]*)\|([^|]*)_ORYSJ/,
            /^([^|]*)\|([^|]*)\|([^|]*)_ORYSI/,

            # Usually none
            /^([^|]*)\|([^|]*)\|([^|]*)_POPTR/,

            # Usually none
            /^([^|]*)\|([^|]*)\|([^|]*)_PHYPA/,
           ]

linenum = 0
skip = false

while line = STDIN.gets
  line.chomp!
  linenum += 1

  if line =~ /^>(.*)/
    header = $1
    if header.size == 0
      STDERR.puts "ERROR: Bad header #{header.inspect} on line #{linenum}"
      exit 1
    end

    if DROPOUTS.collect{|d| true if header =~ d}.include? true
      skip = true
    else
      skip = false
    end
  end

  puts line unless skip

end


if linenum == 0
  STDERR.puts "ERROR: #{SNAME}: Empty input"
  exit(1)
end
