#!/usr/bin/ruby

HEADERS_FILE = "from-mysql-cellwall.headers"

MV = '/bin/mv'

File.open(HEADERS_FILE, 'w') do |h| # Save headers in a file
  ARGV.each do |filename|
    File.open(filename) do |f|
      oldline = f.gets # Remove headers
      h.puts "#{oldline.chomp}\t#{filename}"
      puts "Removed #{oldline.inspect} from #{filename.inspect}"
      File.open("#{filename}.new", 'w') do |g|
        while line = f.gets
          g.puts line  
        end
      end
    end
  
    `#{MV} #{filename}.new #{filename}`
  end
end

STDERR.puts "NOTICE: Removed lines were written into #{HEADERS_FILE}"

