#!/usr/bin/env Rscript

library("ggplot2")

tab_files <- dir()[grep("[.]tab$", dir())]
family_names <- readLines(pipe("./004-get-fam-names"))

get.stats <- function(filename) {
  tab <- read.csv(filename, header=F, sep="\t")
  numseqs <- nrow(tab)

  mean_seq_len = mean(nchar(levels(tab[,2])))
  #mean_seq_len = sprintf("%.1f", mean_seq_len)

  list(numseqs, mean_seq_len)
}

stats <- t(sapply(tab_files, get.stats))

#g <- cbind(stats[,1], rownames(stats), tr(as.data.frame(rep("2009", nrow(stats))))
g2 <- data.frame(
  Families=factor(family_names),
  Number_of_Sequences=as.numeric(stats[,1]),
  Builds=factor(rep("2009_08", nrow(stats)))
                )

# Hide NSI
g2 <- g2[-4,]

pdf("numseq-plot.pdf")
ggplot(g2, aes(Families, Number_of_Sequences, fill = Builds)) +
  geom_bar(position="dodge") + coord_flip(wise=T) +
  opts(axis.text.y=theme_text(angle=0,hjust=1), axis.text.x=theme_text())
dev.off()
