#!/usr/bin/ruby

HOME         = `echo ~`.chomp
SCRIPTS_DIR  = "#{HOME}/.html/cellwall/scripts"
NAME         = File.basename(__FILE__)
FASTA2TAB    = "#{SCRIPTS_DIR}/convert-fasta-to-tab"  # Pipelined
GFF3_TO_TAB  = "#{SCRIPTS_DIR}/convert-gff3-to-tab"    # Not Pipelined
GFF0_TO_TAB  = "#{SCRIPTS_DIR}/convert-gff0-to-tab"    # Not Pipelined
FILETYPE     = "#{SCRIPTS_DIR}/lookup-filetype-from-stream"

MAX_THREADS  = 20

DATE_OPTIONS = "+%Y-%m-%d" # For example 2009-03-23
DATE         = "/bin/date #{DATE_OPTIONS}"

WGET_OPTIONS = "--quiet -O-" # Download quietly to standard out 
WGET         = "/usr/bin/wget #{WGET_OPTIONS}"

ZCAT         = "/bin/zcat"
BZCAT        = "/bin/bzcat"
TEE          = "/usr/bin/tee"
CP           = "/bin/cp"
MV           = "/bin/mv"


OPTIONS      = ['--no-tabs']

SOURCE_MAP   = ARGV[0]

if SOURCE_MAP.nil?
  STDERR.puts "Usage: #{NAME} <source_map_file>"
  exit(1)
end

DOWNLOAD_TIMESTAMP = `#{DATE}`.chomp

def run(cmd, tabulizer, type, out_name)
  return unless out_name =~ /_struct/ # Skip all but this one

  destination =
    "source_#{DOWNLOAD_TIMESTAMP}_#{type.ljust(5,'-')}_#{out_name}"

  if type == "gff" or type == "gff3"
    # SPECIAL CASE: Cannot pipeline the GFF converter, must do in stages
    system("#{cmd} > #{destination}")
    system("#{tabulizer} #{destination}")
    system("#{MV} #{destination}.tab dumps/")
   
  else
    piped_cmd = "#{cmd} | #{TEE} #{destination} " + 
      if OPTIONS.include?('--no-tabs')
        "> /dev/null"
      else 
        "| #{tabulizer} > dumps/#{destination}.tab"
      end

    system(piped_cmd)
  end

  puts destination
end

def download_and_convert_one(name, url)
  download_and_gunzip_cmd = "#{WGET} \"#{url}\""
  loop do
    filetype = `#{download_and_gunzip_cmd} | #{FILETYPE}`.chomp

    if filetype =~ /^FASTA/
      run(download_and_gunzip_cmd, FASTA2TAB, 'fasta', name)
      break

    elsif filetype =~ /^GFF3/
      run(download_and_gunzip_cmd, GFF3_TO_TAB, 'gff3', name)
      break

    elsif filetype =~ /^GFF/
      run(download_and_gunzip_cmd, GFF0_TO_TAB, 'gff', name)
      break

    elsif filetype =~ /^gzip/
     download_and_gunzip_cmd += " | #{ZCAT}" 

    elsif filetype == 'nil'
      STDERR.puts "ERROR: Could not download #{url}"
      break

    else
      STDERR.puts "ERROR: Unknown filetype: #{filetype.inspect} for " +
        "#{download_and_gunzip_cmd.inspect}"
      break

    end

  end
end

File.open(SOURCE_MAP) do |f|
  while line = f.gets

    line.strip!
    next if line.empty? or line =~ /^[\s]*#/
    name, url = line.split(/[ \t]/)
    loop do
      if (Thread.list - [Thread.main]).size < MAX_THREADS
        Thread.new{download_and_convert_one(name, url)}
        break
      else
        sleep 5
      end
    end

  end
end

(Thread.list - [Thread.main]).each {|t| t.join}

