#!/usr/bin/ruby

first_line = true

while line = STDIN.gets
  line.chomp!

  if line =~ /^>/
    puts unless first_line
    print line[1..-1]
    print "\t"
  else
    print line.chomp
  end

  first_line = false
end
puts
