#!/usr/bin/ruby

def parse(line)
  line.chomp!

  # GFF3 names!
  seqid_col, source_col, type_col, start_col, end_col,
    score_col, strand_col, phase_col, attributes_col = line.split("\t")

  #attributes_hash = {}
  #attributes_col.split(';').each do |i|
  #  key, values = i.split('=')
  #  attributes_hash[key] = values.split(',')
  #end

  [seqid_col, source_col, type_col, start_col, end_col,
    score_col, strand_col, phase_col, attributes_col]

end


#keys = ['Alias', 'ID', 'Name', 'Parent']
while line = STDIN.gets
  unless line =~ /^\s*#/
    out = parse(line)

    
    #if (out[-1].keys - keys) != []
    #  raise "Unknown key(s) #{(out[-1].keys - keys).inspect} in #{out.inspect}"
    #end

    #puts (out[0..-2] + []).join("\t") 
    puts out.join("\t") 
  end
end

