#!/usr/bin/ruby

require 'tempfile'
NAME      = File.basename(__FILE__)
FILE_UTIL = "/usr/bin/file"

first_line = ""
loop do
  first_line = STDIN.gets
  puts first_line
  if first_line.nil?
    STDERR.puts "#{NAME}: Possibly comments but No data"
    exit(1)
  end
  break unless first_line =~ /^[\s]*#/
end

if first_line =~ /^>/
  puts "FASTA"
  exit
elsif first_line.split("\t").size == 9
  all_pairs = first_line.split("\t")[8].split(';')
  if all_pairs.collect{|keyval| keyval.include? '='} == [true] * all_pairs.size
    puts "GFF3"
  else
    puts "GFF"
  end
  exit
end

# Does not match any special file types, so it's time to use `file` utility
tempfile = Tempfile.new(NAME)
tempfile.puts first_line

tempfile.flush
type = `#{FILE_UTIL} #{tempfile.path}`

puts type.split(": ")[1]

