#!/usr/bin/ruby

# Usage Example:
#  cat from-mysql-cellwall.headers | \
#    ~/.html/cellwall/scripts/misc-load-tables > \
#    from-mysql-cellwall.load-tables

# See also: ~/.html/cellwall/scripts/misc-remove-all-first-lines

# TYPES_FROM_NAMES = {
#   "to_number(%s, '9')" => [:id],
# 
#    
# }

while line = STDIN.gets
  all = line.chomp.split("\t")
  columns = all[0..-2]
  name = all.last
  if name =~ /from-mysql-cellwall-(.*?).tab/
    name = $1
  end

  puts "copy cellwall.from_mysql_#{name} ( #{columns.join(', ')} ) " +
	"from 'c:\\\\db-dumps/from-mysql-cellwall-#{name}.tab';" # For Windows

  puts "insert into cellwall.#{name} (  #{columns.join(', ')} )"
  puts "select to_number(#{columns.join(",'9'), to_number(")},'9')"
  puts "from cellwall.from_mysql_#{name}"
  puts

end
