#!/bin/bash

set -e

stat code > /dev/null || stat data > /dev/null || \
        (echo "ERROR: You must run this script from the root of the project dir"; exit 1)

~/opt/hmmer-3.1b1/bin/hmmsearch \
  -E 0.1 \
  --tblout data/240-find-matches-in-uniprot/gh43-uniprot-hits \
  data/230-build-hmm/gh43.hmm \
  data/120-download-uniprot/uniprot_sprot_plus_trembl.fasta \
  > data/240-find-matches-in-uniprot/gh43-uniprot-hits.human
