#!/usr/bin/ruby

SDIR = File.dirname(File.expand_path(__FILE__))
Dir.chdir SDIR

Dir.glob("*_fasta_*").each do |file_name|
  next if file_name =~ /tab$/
  puts file_name
  `cat #{file_name} | ./convert-fasta-to-tab > #{file_name}.tab`
end
