#!/usr/bin/ruby

DROPOUTS = [/^([^|]*)\|([^|]*)\|([^|]*)_ARATH/,
            /^([^|]*)\|([^|]*)\|([^|]*)_ORYSA/,
            /^([^|]*)\|([^|]*)\|([^|]*)_POPTR/,
            /^([^|]*)\|([^|]*)\|([^|]*)_PHYPA/,
           ]

linenum = 0
skip = false

while line = STDIN.gets
  line.chomp!
  linenum += 1

  if line =~ /^>(.*)/
    header = $1
    if header.size == 0
      STDERR.puts "ERROR: Bad header #{header.inspect} on line #{linenum}"
      exit 1
    end

    if DROPOUTS.collect{|d| true if header =~ d}.include? true
      skip = true
    else
      skip = false
    end
  end

  puts line unless skip

end
