#!/usr/bin/ruby

SDIR = File.dirname(File.expand_path(__FILE__))
DESTINATION = File.expand_path(".")


if !(DESTINATION =~ /-dropout$/)
  STDERR.puts "WARNING: You are in #{File.basename(DESTINATION)}"
  STDERR.puts "WARNING: You are not in a Dropout dir!"
  puts "Proceed anyway? (Press 'y' and Enter to proceed)"
  a = gets.chomp
  exit unless a == "y"
end


TARGETS = 
  Dir.glob("*_fasta_uniprot*_trembl") + 
  Dir.glob("*_fasta_uniprot*_sprot-")

if TARGETS.size != 2
 STDERR.puts "ERROR: Invalid number of files matched " +
 "with the reqired filename pattern:\n  " + TARGETS.join("\n  ")
end



TARGETS.each do |t|
  puts `time cat #{t} | ./create-dropout-from-fasta > #{t}-dropout`
  `rm #{t}`
end

`./SEQ_COUNTS.get > ./SEQ_COUNTS`
