#!/usr/bin/ruby

SDIR = File.dirname(File.expand_path(__FILE__))
DESTINATION = "../#{SDIR.split('/').last}-dropout"

if File.exists? DESTINATION
  puts "WARNING: Destination #{DESTINATION} already exists!"
  puts "Proceed anyway? (Press 'y' and Enter to proceed)"
  a = gets.chomp
  exit unless a == "y"
end

if DESTINATION =~ /-dropout-dropout/
  STDERR.puts "ERROR: You are already in a dir with a Dropout"
  exit(1)
end

Dir.chdir SDIR

TARGETS = 
  Dir.glob("*_fasta_uniprot*_trembl") + 
  Dir.glob("*_fasta_uniprot*_sprot-")

if TARGETS.size != 2
 STDERR.puts "ERROR: Invalid number of files matched " +
 "with the reqired filename pattern:\n  " + TARGETS.join("\n  ")
end

`cp -r #{SDIR} #{DESTINATION}`



Dir.chdir DESTINATION

TARGETS.each do |t|
  puts `time cat #{t} | ./create-dropout-from-fasta > #{t}-dropout`
  `rm #{t}`
end

`rm ./tabs/*.tab`
`./tabs/convert-all-to-tab`
`mv *.tab tabs/`

`./SEQ_COUNTS.get > ./SEQ_COUNTS`
`./tabs/TAB_COUNTS.get > ./tabs/TAB_COUNTS`
