CREATE TABLE stage.from_mysql_dblink (id VARCHAR, section VARCHAR, sequence VARCHAR, db VARCHAR, href VARCHAR, updated VARCHAR);
CREATE TABLE stage.from_mysql_db (id VARCHAR, genome VARCHAR, name VARCHAR, db_type VARCHAR, updated VARCHAR);
CREATE TABLE stage.from_mysql_family (id VARCHAR, grp VARCHAR, rank VARCHAR, name VARCHAR, abrev VARCHAR, updated VARCHAR);
CREATE TABLE stage.from_mysql_genome (id VARCHAR, name VARCHAR, updated VARCHAR);
CREATE TABLE stage.from_mysql_groups (id VARCHAR, parent VARCHAR, rank VARCHAR, name VARCHAR, updated VARCHAR);
CREATE TABLE stage.from_mysql_idxref (sequence VARCHAR, accession VARCHAR);
CREATE TABLE stage.from_mysql_parameters (id VARCHAR, section VARCHAR, others VARCHAR, reference VARCHAR, name VARCHAR, value VARCHAR, updated VARCHAR);
CREATE TABLE stage.from_mysql_search (id VARCHAR, name VARCHAR, s_type VARCHAR, genome VARCHAR, db VARCHAR, query VARCHAR, updated VARCHAR);
CREATE TABLE stage.from_mysql_species (id VARCHAR, genus VARCHAR, species VARCHAR, sub_species VARCHAR, common_name VARCHAR, updated VARCHAR);
CREATE TABLE stage.from_mysql_subfamily (id VARCHAR, family VARCHAR, rank VARCHAR, name VARCHAR, updated VARCHAR);
