#!/usr/bin/env Rscript

library("ggplot2")

family_names <- readLines(pipe("./004get-fam-names"))

get.stats <- function(filename) {
  print(filename)

  tab <- read.csv(filename, header=F, sep="\t")
  numseqs <- nrow(tab)

  mean_seq_len = mean(nchar(levels(tab[,2])))
  #mean_seq_len = sprintf("%.1f", mean_seq_len)

  list(numseqs, mean_seq_len)
}

g <- data.frame(Families=factor(),
  Number_of_Sequences=numeric(),
  Builds=factor())

builds_list <- dir()[grep("^20", dir())]
for (build_name in builds_list) {
  setwd(build_name)

  tab_files <- dir()[grep("[.]tab$", dir())]
  stats <- t(sapply(tab_files, get.stats))
  
  #g <- cbind(stats[,1], rownames(stats), tr(as.data.frame(rep("2009", nrow(stats))))
  g2 <- data.frame(
    Families=factor(family_names),
    Avg_Sequence_Length=as.numeric(stats[,2]),
    Builds=factor(rep(build_name, nrow(stats))))
  
  # Hide NSI
  g2 <- g2[-4,] 

  g <- rbind(g, g2)

  setwd("..")
}

pdf("numseq-plot.pdf")
ggplot(g, aes(Families, Avg_Sequence_Length, fill = Builds)) +
  geom_bar(position="dodge") + coord_flip(wise=T) +
  opts(axis.text.y=theme_text(angle=0,hjust=1), axis.text.x=theme_text())
dev.off()
